### ISSUE TITLE
Prototype template uses random Basic-Auth password

### ISSUE THREAD

**Issue by xoen** [ministryofjustice/cloud-platform-cli#165]
### Background

Hello,

Our designer has used the CLI to generate a new prototype environment yesterday.
The CLI asked for username and password to be used for HTTP Basic Authentication.

Once deployed I noticed that these credentials were not working, so I manually updated the corresponding k8s `Secret` to fix this.
However today the password has changed again.

### Source of the issue
Upon investigation I noticed that the password has changed again and that in fact the template generated by the CLI is writing a random password in the secret:

```hcl
resource "kubernetes_secret" "basic-auth" {
  # ...

  data = {
    username = var.basic-auth-username
    password = random_password.password.result
  }
}
```

This is coming from the template file here: https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespace-resources-cli-template/resources/prototype/basic-auth.tf

### Problem
It was surprising that CLI asked for username/password but a random password is used instead.

**Comment by razvan-moj** [comment]
reverted random pass change, will revisit after some more thought
