### ISSUE TITLE
decode-secret adding (MISSING) to client secret when decoding

### ISSUE THREAD

**Issue by markreesmoj** [ministryofjustice/cloud-platform-cli#75]
steps to reproduce

Compare the output from

kubectl -n hmpps-tier-preprod get secrets hmpps-tier -o json | jq ".data.OAUTH_CLIENT_SECRET" -r | base64 -D

and 

cloud-platform decode-secret -n hmpps-tier-preprod -s hmpps-tier |  jq ".data.OAUTH_CLIENT_SECRET" -r 

I don't want to post the secret in here but the output of the second command is quite different from the first and contains the string
(MISSING)

**Comment by davidread** [comment]
We reaffirmed we want this feature still, for [these reasons](https://github.com/ministryofjustice/cloud-platform/issues/2193#issuecomment-801021148)

**Comment by jasonBirchall** [comment]
Hi @markreesmoj this is solved indirectly in 1.17.0. I'm fairly certain it was the way we passed a missing error value. A recent refactor solved this.

If it's still a problem, please feel free to re-open or dm me on slack.
